### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by JoBalk** [raburton/tabscroller#1]
I'm running Ubuntu 16.04 with Gnome 3.18.5. 
Instead of scrolling the normal right-click dialog opens up.

**Comment by raburton** [comment]
Thank you for the feedback.
On further investigation I have found the problem and it isn't unique to this addon. It seems that on Linux and OSX the right click menu is triggered on mouse down and on windows it is triggered on mouse up. This allows us to detect the wheel before the menu appears, cancel it and scroll the tabs. Various other gesture addons have the same problem and have gone for messy work-arounds like disabling the context menu on single right click and adding a new handler to open it only on a double click.
There is a patch for Firefox which many people are pushing for the inclusion of: https://bugzilla.mozilla.org/show_bug.cgi?id=1360278
I will update the description of the addon to make this clear - that it does not yet work but hopefully will once this bug is fixed.

**Comment by JoBalk** [comment]
Ok, thank you for the information and your effort to bring this feature back to Firefox. Hopefully Mozilla will fix this soon.

**Comment by raburton** [comment]
As per the Mozilla bug tracker, linked above, the necessary feature has been added to Firefox 59. There is a possibility it might also make it into 58 as well, but that's still being negotiated. The change in behaviour is not default and requires a setting to be enabled in about:config. So hopefully this should work in a few weeks time. Are you able to test with one of the nightly builds of 59?

**Comment by raburton** [comment]
Ok, got it tested myself. Working fine in Firefox 59 on Linux, with the new config option set. Hopefully they will pull the fix into 58 as well so it won't be so long to wait. Also, there is a bug open to expose the new config option to addons, meaning I can get the plugin to automatically set that option itself.

**Comment by raburton** [comment]
I've added support for Linux/OSX, which will work from v59 straight off and v58 (current beta) with a manual config change (hopefully by the time v58 is released it'll work straight off there too).

**Comment by JoBalk** [comment]
Thank you. What is the name of the new config-option? Is the patch already included in the v58 beta or do I have to build it by myself?

**Comment by raburton** [comment]
The new config option, and the api to allow addons to set it, is in v58 beta 7. If you have that version it should just work with the latest build of tabscroller (v1.0.5), no need to manually make any settings changes.

**Comment by DragoonAethis** [comment]
Everything works just fine on Linux with FF 58 and TabScroller 1.0.5, no configuration needed. This can be closed.

**Comment by raburton** [comment]
Thanks for the feedback.
